---
- hosts: web
  user: vagrant
  sudo: yes
  gather_facts: no
  tasks:
    - name: Init iptables.
      template: src=iptables_tmpl.j2 dest=/etc/sysconfig/iptables

    - name: iptables restart
      service: name=iptables state=started enabled=yes
