---
- hosts: web
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install php
      yum: name={{ item }} state=latest enablerepo=remi,remi-php56
      with_items:
        - curl
        - php
        - php-devel
        - php-mbstring
        - php-gd
        - php-cli
        - php-xml
        - php-dbg
        - php-pecl-xdebug
        - php-pecl-mailparse
        - php-curl
        - php-process
        - php-pear
        - php-pdo
        - php-mysql
        - php-pgsql
        - php-pecl-apcu
        - php-intl    # 64bit
      notify: restart apache

#    - name: Install pear libraries.
#      always_run: yes
#      shell: pear upgrade; pear install {{ item }}
#      with_items:
#        - MDB2_Driver_pgsql-1.4.1
#        - MDB2-2.5.0b5
#        - Mail
#        - Mail_Mime
#        - Mail_mimeDecode
#      notify: restart apache

    - name: Setting Timezone php
      lineinfile: dest=/etc/php.ini state=present regexp="^;date.timezone" line="date.timezone = Asia/Tokyo"
      always_run: yes
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
